notifications:
  email: false

env:
  global:
  - TERM=dumb
  - secure: XTLnbmciC6vrmK8vgN3xqIrQnHSrKNpsExNg7m2vs899ftLshJFAA20lEdw8LCU2CKhe2xlG5cPGxOkyeUEYtZm9YAUyqO7khqPFolgw0u2/J7e0YIU66nHj5H7rqdiRTOEDO37018SuqNULptMRPCpOMvyUUtW1u+r6f1e+wfh8Md1dP17n5TvozkoMdbuMtoUHcYtAPtGOUP5THDlgzYJakdYllwSNKhUwwoMS5FWAAO/12Cb5hcFVt/EAQQPhWL8TZhMF9HlFdyXMtQ3ymOY6e8ZqLooILYgBkgDVnOwDN3ZIUyj1tw2HRvV3uCx3Hkd+Aj7IsbxfslWL1qJlyoyDOCUGMo4yBH+Fq0mYusFS7gHNjbF8UXeDEFDoHtnimRUXyeSNVOGtk+I/wXTCWgy3bL3iVFwneLw6DzOiVQA3lhBxasps7swgNFGJSs49AB51clTbzW7JbCHjPBip9gX57Rc2rmnWS7uDmVzQStHf5LDWUq4V20Ne/lv7bJpj2iOkVCcwHKHFzF7WMJGaspflSqyy5TxST4e/4YsjjeJ5tuxK/Znz5dMHkv4qGY/NJEVCdKU7LTSNfpcK0Qkh1zbjjD4JbmnzvZdepBBiBy3sQ2E90QjnoJWyn5zS44azGVo4KOcXGp1d73yE/10FPsIZI0WpiHVbMLrRu3MaTio=

language: java
jdk:
- oraclejdk8
#- oraclejdk10

service:
- docker

addons:
  apt:
    update: true
    sources:
    - google-chrome
    packages:
    - docker-ce
    - google-chrome-stable
    - libappindicator1
    - fonts-liberation
    - bash
    - curl
    - libxml2-utils

install: true
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
#
- sudo add-apt-repository universe -y >/dev/null
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends
  tree jq python-pip curl bash sudo >/dev/null
#
- sudo pip install docker-compose httpie >/dev/null 2>&1
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 3000 80 >/dev/null
#
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - >/dev/null
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends yarn >/dev/null

script:
- export root=$(pwd)
- ./mvnw >/dev/null
- ./mvnw -pl docker >/dev/null
- ./mvnw -pl docker -P down
- ./mvnw -pl docker -P up
- ./mvnw -pl docker -P up-tail &
- sleep 100
- ./mvnw -pl docker -P down

before_deploy:
- cd ${root}
- ./mvnw -pl docs
- mkdir -p ./docs/target/generated-docs
- cp -Rf ./docs/target/generated-docs/index.html ./docs/target/generated-docs/404.html

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: docs/target/generated-docs
  target_branch: gh-pages

before_cache:
- for item in $(find ~/.gradle -name "*.lock") ;
    do sudo rm -rf $item ;
  done
- for item in $(find ./ -name "*.lock") ;
    do sudo rm -rf $item ;
  done

cache:
  directories:
  - $HOME/.docker
  - $HOME/.gradle
  - $HOME/.m2
