version: '2.1'

services:

  hub:
    depends_on:
      jboss:
        condition: service_healthy
    image: selenium/hub:3.14.0-beryllium
    ports: ['4444:4444']
    networks:
      backing-services:
        aliases:
        - hub
        - selenium-hub
        - hub.daggerok.github.com
        - selenium-hub.daggerok.github.com
    healthcheck:
      test: curl -v http://127.0.0.1:4444/grid/console/
      timeout: 1s
      retries: 22
    restart: unless-stopped

  chrome:
    depends_on:
      hub:
        condition: service_healthy
    image: selenium/node-chrome-debug:3.14.0-beryllium
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    ports: ['5900']
    networks:
      backing-services:
        aliases:
        - chrome
        - node-chrome-debug
        - chrome.daggerok.github.com
        - node-chrome-debug.daggerok.github.com
    restart: unless-stopped
    #shm_size: 2g

  oracle:
    image: daggerok/oracle:xe
    shm_size: 1g
    environment:
      ORACLE_PWD: password
      APEX_PORT: 8080
    ports: ['1521:1521']
    volumes: ['oracle-data:/u01/app/oracle/oradata']
    healthcheck:
      test: curl -uSYSTEM:$$ORACLE_PWD -v http://127.0.0.1:$$APEX_PORT//apex/
      timeout: 2s
      retries: 100
    networks:
      backing-services:
        aliases:
        - o
        - db
        - oracle
        - o.daggerok.github.com
        - db.daggerok.github.com
        - oracle.daggerok.github.com

  jboss:
    image: 127.0.0.1:5000/jboss-docker-e2e-solution/jboss
    links: [oracle]
    depends_on:
      oracle:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-legacy-java-ee-app
    volumes: ['jboss-data:/home/appuser']
    ports: ['8080:8080']
    networks:
      backing-services:
        aliases:
        - j
        - jb
        - app
        - jboss
        - j.daggerok.github.com
        - jb.daggerok.github.com
        - app.daggerok.github.com
        - jboss.daggerok.github.com

volumes:
  oracle-data: {}
  jboss-data: {}

networks:
  backing-services:
    driver: bridge
